name: Django CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/
            git clone git@github.com:cpcO7/ResT.git new_res/backend
            cd new_res/backend/
            docker-compose build
            docker-compose up -d

#            systemctl daemon-reload
#            systemctl restart rest.service
#            systemctl reload nginx.service
#            chmod +x ./deploy/migration/start
#            . ./deploy/migration/start

