name: Django CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/rest/backend
            cd /var/www/rest/backend
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/cpcO7/rest.git 
            fi
            sleep 10s
            ./deploy/compose/start
