name: Django CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/samariddins_project/project1/backend
            git pull
#            pip3 install -r requirements.txt
            chmod +x deploy/migration/start
            systemctl restart rest.service
            systemctl reload nginx.service
            systemctl restart rest_celery.service
            systemctl restart rest_flower.service
#            mv deploy/bot/rest_bot.service /etc/systemd/system
            systemctl enable rest_flower.service
            systemctl start rest_flower.service            
#            mv deploy/bot/rest_bot.conf /etc/nginx/sites-enabled
            systemctl reload nginx.service


