name: Django CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/samariddins_project/project1/backend
            git pull
            python manage.py makemigrations
            python manage.py migrate
            systemctl restart rest.service
            systemctl reload nginx.service
            systemctl restart rest_celery.service
            systemctl restart rest_flower.service

